# A list of devices you want to take the screenshots from
devices([
  "iPhone 17 Pro Max",
  "iPad Pro 13-inch (M5)",
])

# Single source of truth for languages: folders under fastlane/metadata
# Allows LANGUAGES env var to filter (e.g. "en-US uk")
def all_languages
  Dir["./fastlane/metadata/*"].select { |f| File.directory?(f) }.map { |d| File.basename(d) }
end

if ENV['LANGUAGES'] && !ENV['LANGUAGES'].strip.empty?
  filter = ENV['LANGUAGES'].split
  languages(filter)
else
  languages(all_languages)
end

scheme("Screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
